# Generated by Django 4.2.4 on 2023-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="number"
                    ),
                ),
                ("wanted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "License plate",
            },
        ),
    ]
